apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic1111
  labels:
    app: automatic1111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic1111
  template:
    metadata:
      labels:
        app: automatic1111
    spec:
      containers:
      - name: automatic1111
        image: ubuntu:noble
        ports:
        - containerPort: 7860
        command: ["/bin/sh"]
        args: 
        - -c
        - |
          set -x
          if [ "$EUID" -ne 0 ]
            then echo "Please run as root"
            exit
          fi

          if ! command -v adduser &> /dev/null; then
            echo "adduser command not found. Installing..."
            apt update
            apt install -y adduser
          fi

          # Create user and add to sudo group
          adduser sduser
          if [ $? -ne 0 ]; then
            echo "Failed to create user sduser"
            exit 1
          fi

          usermod -aG sudo sduser

          apt update
          apt install wget software-properties-common git libgl1 libglib2.0-0 -y
          add-apt-repository ppa:deadsnakes/ppa
          apt update
          apt install python3.10 python3.10-venv -y

          git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
          chown -R sduser:sduser stable-diffusion-webui
          cd stable-diffusion-webui
          echo 'export ACCELERATE="True"' >> webui-user.sh

          # git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
          # cd stable-diffusion-webui
          # python -m venv venv
          # source venv/bin/activate
          # python -m pip install --upgrade pip wheel

          # It's possible that you don't need "--precision full", dropping "--no-half" however crashes my drivers
          # TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half

          su sduser -c "python3.10 -m venv venv && \
          source venv/bin/activate && \
          ./webui.sh --listen  --api  --api-log --nowebui"
        resources:
          claims:
          - name: gpu
            request: mps-gpu
      resourceClaims:
      - name: gpu
        resourceClaimName: shared-gpu
---
apiVersion: v1
kind: Service
metadata:
  name: automatic1111-service
spec:
  selector:
    app: automatic1111
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7861
