apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic1111
  labels:
    app: automatic1111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic1111
  template:
    metadata:
      labels:
        app: automatic1111
    spec:
      containers:
      - name: automatic1111
        image: ubuntu:noble
        ports:
        - containerPort: 7860
        command: ["/bin/sh"]
        args: 
        - -c
        - |
          if [ "$EUID" -ne 0 ]
            then echo "Please run as root"
            exit
          fi

          if ! command -v adduser &> /dev/null; then
            echo "adduser command not found. Installing..."
            apt update
            apt install -y adduser
          fi

          # Create user and add to sudo group
          adduser sduser
          if [ $? -ne 0 ]; then
            echo "Failed to create user sduser"
            exit 1
          fi

          usermod -aG sudo sduser
          
          apt update
          apt install wget software-properties-common git python3 python3-venv libgl1 libglib2.0-0 -y
          add-apt-repository ppa:deadsnakes/ppa
          apt update
          apt install python3.10 -y
          
          wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh
          chown -R sduser:sduser webui.sh
          
          sleep 3600
          su sduser -c "python3.10 -m venv venv && \
          source venv/bin/activate && \
          ./webui.sh"
        resources:
          claims:
          - name: gpu
      resourceClaims:
      - name: gpu
        resourceClaimName: single-gpu
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaim
metadata:
  name: single-gpu
spec:
  devices:
    requests:
    - name: gpu
      deviceClassName: gpu.nvidia.com
---
apiVersion: v1
kind: Service
metadata:
  name: automatic1111-service
spec:
  selector:
    app: automatic1111
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
