apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaim
metadata:
  name: shared-gpu
spec:
  devices:
    requests:
    - name: shared-gpu
      deviceClassName: gpu.nvidia.com
#      selectors:
#      - cel:
#          expression: |
#            device.attributes['gpu.nvidia.com'].productName.lowerAscii().matches('^.*t4.*$')
