apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-gpu
  labels:
    app: ollama-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-gpu
  template:
    metadata:
      labels:
        app: ollama-gpu
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        env:
        - name: OLLAMA_FLASH_ATTENTION
          value: "1"
        ports:
        - containerPort: 11434
        command: ["/bin/sh"]
        args: ["-c", "ollama serve"]
        resources:
          claims:
          - name: gpu
            request: mps-gpu
      resourceClaims:
      - name: gpu
        resourceClaimName: mps-gpu
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-gpu-service
spec:
  selector:
    app: ollama-gpu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
